import type { Metadata } from 'next'
import { Header } from '@/components/Header'

export const metadata: Metadata = {
  title: 'Privacy — Scour',
}

const UPDATED = 'July 14, 2026'

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="mx-auto flex w-full max-w-2xl flex-col gap-8 px-6 py-12 sm:py-20">
        <div className="flex flex-col gap-2">
          <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
          <p className="font-mono text-[11px] uppercase tracking-wider text-fg-subtle">
            Last updated {UPDATED}
          </p>
        </div>

        <div className="flex flex-col gap-6 text-sm leading-relaxed text-fg-muted">
          <p>
            Scour is a shopping search tool that looks up products across retailer sites
            (Amazon, eBay, Etsy, Best Buy, Shopify/WooCommerce storefronts, Reddit, Slickdeals,
            and others) and shows the results side by side. This page explains what happens to
            your data when you use it, on the web or in the Android app.
          </p>

          <Section title="No accounts">
            <p>
              Scour does not have user accounts, sign-in, or passwords. There is no personal
              profile tied to you as a person. Saved/wishlist items and enabled sources are
              stored in Scour&apos;s own database and are currently shared across everyone using
              this instance of the app — they are not private to an individual device or
              account.
            </p>
          </Section>

          <Section title="What Scour processes">
            <ul className="list-disc space-y-1.5 pl-5">
              <li>
                <strong className="text-fg">Search queries.</strong> The text you search is sent
                to Scour&apos;s server, which forwards it to the enabled retailer sources to fetch
                matching listings, and to Scour&apos;s AI layer (Groq and/or Google Gemini) to
                parse the query, judge whether listings match, or answer copilot/mission
                questions when you use those features. Retailers and AI providers process that
                text under their own terms; Scour does not sell it.
              </li>
              <li>
                <strong className="text-fg">Wishlist entries and price-alert thresholds</strong>{' '}
                you add, stored in Scour&apos;s database until removed.
              </li>
              <li>
                <strong className="text-fg">Standard server logs</strong> (IP address, request
                timestamps, pages requested) generated by normal web server operation, used only
                for operating and securing the service.
              </li>
            </ul>
          </Section>

          <Section title="What Scour does not do">
            <ul className="list-disc space-y-1.5 pl-5">
              <li>No unified checkout — Scour never collects payment details. Every &quot;buy&quot;
                deep-links to the retailer&apos;s own page, where their privacy/payment terms apply.</li>
              <li>No advertising or tracking cookies, no analytics SDKs, no ad networks.</li>
              <li>No sale of personal data.</li>
            </ul>
          </Section>

          <Section title="Third parties">
            <p>
              Depending on which sources are enabled, a search may reach: eBay, Etsy, Best Buy,
              Shopify/WooCommerce storefronts, Reddit, Slickdeals, and other retailer sites, plus
              Groq and Google Gemini for the AI features. Each handles data under its own privacy
              policy — Scour only relays what&apos;s needed to answer your request.
            </p>
          </Section>

          <Section title="Android app">
            <p>
              The Android app is a thin wrapper around this same website — it opens
              scour&apos;s live site in an app shell rather than shipping a separate backend or
              collecting additional data itself. Everything above applies equally there.
            </p>
          </Section>

          <Section title="Changes">
            <p>
              This is a small, actively-developed project — this policy may change as features
              change. Check back here for updates.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about this policy: reach the developer via the contact link in the Play
              Store listing.
            </p>
          </Section>
        </div>
      </main>
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-sm font-semibold uppercase tracking-[0.1em] text-fg">{title}</h2>
      {children}
    </section>
  )
}
